### ISSUE TITLE
File not found: /bbx/input/biobox.yaml

### ISSUE THREAD

**Issue by richardgoater** [bioboxes/shovill#5]
Doesn't matter what command is provided, the above is all the output I can get. Applies for both locally-built images and the image on docker hub. Any thoughts?

**Comment by michaelbarton** [comment]
Hi @richardgoater, this shovill image uses the biobox interface. We "hope" this simplifies running bioinformatics software because all software of the same type has the same interface. There's documentation here:

http://bioboxes.org/docs/assemble-a-genome/

In short, after you have installed the bioboxes python interface you can use the command:

```
biobox run \
  short_read_assembler \
  bioboxes/shovill \
  --input reads.fq.gz \
  --output contigs.fa
```

If you're not too keen on using this, you can still use the base image by overriding the entrypoint in the image using the docker `--entrypoint` command.

cc @tseemann

**Comment by richardgoater** [comment]
Hi Michael, thanks very much for the tip.

**Comment by michaelbarton** [comment]
Thanks Richard.
